### ISSUE TITLE
🚀 [Feature]: Export db option to reuse for 3rd modules.

### ISSUE THREAD

**Issue by jsonchou** [gofiber/storage#1006]
### Feature Description

https://github.com/gofiber/storage/blob/main/redis/redis.go

Storage module is a pure operation api. 

s.Get,Set,Delete...

How about export `s.Db` `redis.Client` option for 3rd modules. 
Otherwise it would have to create a extra new client instance.

**Comment by gaby** [comment]
@jsonchou We plan on allowing re-using connections as part of #967

**Comment by jsonchou** [comment]
[https://github.com/gofiber/storage/issues/967](url)
