### ISSUE TITLE
🤗 [Question]: minio client upload file error

### ISSUE THREAD

**Issue by hasanparasteh** [gofiber/storage#1075]
### Question Description

I want to upload a multipart form data file into minio but the problem is that when i upload it i got net/http: HTTP/1.x transport connection broken: http: ContentLength=104130 with Body length 0 error. how can i resolve it? where's it's comming from?

i use `github.com/minio/minio-go/v7 v7.0.63` & `github.com/gofiber/storage/minio v0.1.0` drivers to connect to minio

### Code Snippet (optional)

```go
func UploadIdentityVideo(ctx *fiber.Ctx) error {
	form, err := ctx.MultipartForm()
	if err != nil {
		return err
	}

	file := form.File["file"][0]
	//if err != nil {
	//	return ctx.Status(422).JSON(models.GenericResponse{
	//		Result:  false,
	//		Message: "We were not able upload your attachment",
	//	})
	//}

	if file.Size > utils.MaxFileSize || file.Size < utils.MinFileSize {
		return ctx.Status(422).JSON(models.GenericResponse{
			Result:  false,
			Message: "File Size Error",
		})
	}

	src, err := file.Open()
	defer src.Close()
	if err != nil {
		return ctx.Status(500).JSON(models.GenericResponse{
			Result:  false,
			Message: err.Error(),
		})
	}

	format, err := utils.GetFileFormatFromFile(src)
	if err != nil {
		return ctx.Status(500).JSON(models.GenericResponse{
			Result:  false,
			Message: "Failed to read file format",
		})
	}

	if !utils.VideoAllowedFormats[file.Header.Get("Content-Type")] || !utils.VideoAllowedFormats[format] {
		return ctx.Status(400).JSON(models.GenericResponse{
			Result:  false,
			Message: "Video Format Not Allowed",
		})
	}

	user := ctx.Locals("user").(*jwt.Token)
	claims := user.Claims.(jwt.MapClaims)

	userId := claims["userId"]
	if userId == nil {
		return ctx.Status(412).JSON(models.GenericResponse{
			Result:  false,
			Message: "JWT ERROR",
		})
	}
	userIdString := strconv.FormatFloat(userId.(float64), 'f', 0, 64)

	fileId, err := utils.CreateFileID(src, userIdString)
	if err != nil {
		return ctx.Status(500).JSON(models.GenericResponse{
			Result:  false,
			Message: err.Error(),
		})
	}

	minioClient := ctx.Locals("minio").(*config.MinIOClients)
	filename := utils.CreateFileName(userIdString, hex.EncodeToString(fileId), utils.GetFileExtension(file.Filename))
	_, err = utils.UploadIntoMinIO(minioClient.VideoStorage.Conn(), filename, file.Size, src, config.VideoBucketName)
	if err != nil {
		return ctx.Status(500).JSON(models.GenericResponse{
			Result:  false,
			Message: err.Error(),
		})
	}

	return ctx.Status(200).JSON(models.UploadedResponse{
		Result: true,
		FileId: hex.EncodeToString(fileId),
	})
}


func UploadIntoMinIO(client *minio.Client, fileId string, fileSize int64, file multipart.File, bucket string) (minio.UploadInfo, error) {
	return client.PutObject(
		context.Background(),
		bucket,
		fileId,
		file,
		fileSize,
		minio.PutObjectOptions{},
	)
}
```

### Checklist:

- [X] I agree to follow Fiber's [Code of Conduct](https://github.com/gofiber/fiber/blob/master/.github/CODE_OF_CONDUCT.md).
- [X] I have checked for existing issues that describe my questions prior to opening this one.
- [X] I understand that improperly formatted questions may be closed without explanation.

**Comment by gaby** [comment]
@mstgnz Can you help with this issue? Thanks

**Comment by mstgnz** [comment]
@hasanparasteh  

I don't know what file size you're trying to upload, but I can give information about default definitions. You can do your tests again according to this information.

Firstly, you are working as multipart, but you are actually using a single file.
```go
file := form.File["file"][0]
```
Important Note: Fiber BodyLimit is 4MB by default.

And If you look at the Minio PutObject description. You will see that it does a different operation for files larger than 16MB.

> PutObject creates an object in a bucket.
> You must have WRITE permissions on a bucket to create an object.
> For size smaller than 16MiB PutObject automatically does a single atomic PUT operation.
> 
> For size larger than 16MiB PutObject automatically does a multipart upload operation.
> 
> For size input as -1 PutObject does a multipart Put operation until input stream reaches EOF. Maximum object size that can be uploaded through this operation will be 5TiB.
> WARNING: Passing down '-1' will use memory and these cannot be reused for best outcomes for PutObject(), pass the size always.
> NOTE: Upon errors during upload multipart operation is entirely aborted.

I hope this information has been helpful.

**Comment by mstgnz** [comment]
yes, you were not using the fiber store anyway. you were using the Minio client directly.
