### ISSUE TITLE
🤗 [Question]:  what is the way ot use mysql connection in handler function

### ISSUE THREAD

**Issue by kousherAlam** [gofiber/storage#1127]
### Question Description

Hi guys, 
I may be wrong, please help me to understand !

In the docs there are example code  of how we can setup a mysql connection but i can't find any docs of how should i use those connection in the handler function. 

Although i find this text "Premade storage drivers that implement the Storage interface, designed to be used with various Fiber middlewares." 

So is it only to used in middleware ? If i can use those in middleware then why not in handler as i understand middleware is nothing but stack of handler function. 

Thanks

### Checklist:

- [X] I agree to follow Fiber's [Code of Conduct](https://github.com/gofiber/fiber/blob/master/.github/CODE_OF_CONDUCT.md).
- [X] I have checked for existing issues that describe my questions prior to opening this one.
- [X] I understand that improperly formatted questions may be closed without explanation.

**Comment by ReneWerner87** [comment]
here is the documentation
https://docs.gofiber.io/storage/mysql_v1.x.x/mysql/

initialize the storage outside the handler and use the storage instance in the middlewares or simply in the handler to use the functionality of our key value store

you can also do more complex things with the connection, which you get via the `Conn` method

**Comment by gaby** [comment]
User never responded back, stale.
