### ISSUE TITLE
🚀 [Feature]: ClickHouse Implementation

### ISSUE THREAD

**Issue by mirusky** [gofiber/storage#1204]
### Feature Description

I'd like to use [Clickhouse](https://clickhouse.com/) as storage layer and having control over the [table engine](https://clickhouse.com/docs/en/engines/table-engines) being used so I could store into different places effortless.

### Code Snippet (optional)

```go
package main

import "github.com/gofiber/storage/clickhouse"

func main() {
  store := clickhouse.New(clickhouse.Config{
	Host:      "127.0.0.1",
	Port:      9000,
	Username:  "",
	Password:  "",
	Engine: clickhouse.Memory
  })
}
```

### Checklist:

- [X] I agree to follow Fiber's [Code of Conduct](https://github.com/gofiber/fiber/blob/master/.github/CODE_OF_CONDUCT.md).
- [X] I have checked for existing issues that describe my suggestion prior to opening this one.
- [X] I understand that improperly formatted feature requests may be closed without explanation.

**Comment by luk3skyw4lker** [comment]
I'll work on that!

**Comment by gaby** [comment]
@luk3skyw4lker Go driver is here https://github.com/ClickHouse/clickhouse-go seems the native interface is faster than the SQL one. The http one is experimental

**Comment by luk3skyw4lker** [comment]
@gaby thanks for finding it! I claimed the issue and was going to start looking for a driver now

**Comment by luk3skyw4lker** [comment]
I'm having some trouble executing the create table statement and I'm not finding any reference in their docs, so I opened an issue in the go client repository and will be waiting for an answer. Here's the issue: https://github.com/ClickHouse/clickhouse-go/issues/1238

**Comment by luk3skyw4lker** [comment]
Turns out this isn't a thing in Clickhouse itself so I will have to come up with something different for this feature, I'll be working on some ideas and wil put up a PR soon

**Comment by gaby** [comment]
@luk3skyw4lker What was the issue?

**Comment by luk3skyw4lker** [comment]
@gaby the issue is that when creating the table inside the adapter (like all the other adapters do) you don't have a native way to safely bind a engine parameter.

**Comment by luk3skyw4lker** [comment]
I made everything work out, only missing a few docs, will send a PR this week!
