### ISSUE TITLE
🚀 [Feature]: Adding a deletion function with wildcard for the redis package

### ISSUE THREAD

**Issue by okoseisback** [gofiber/storage#1267]
### Feature Description

In the project I developed, there are multiple users, and we store users on the Redis side based on prefixes. And sometimes we need to delete the information we store in Redis.

You can think of an example key like this;
user:{user.guid}:info
user:{user.guid}:preferences
user:{user.guid}:addresses
etc.

I know that this can be done with redis.Keys() and redis.Del(), but it works quite slow in terms of performance. Therefore, I think it would be better to use a function like this based on the package I previously used in NodeJS.

E.g npm pkg:
https://github.com/galanonym/redis-delete-wildcard/blob/master/index.js

The example usage of the function I mentioned would be as follows:
```
count, err := redis.DelWild("user:6e7c5b62-1d4d-4f6e-bb6d-2e1a2c3d4e5f")
if err != nil {
   fmt.Print(err)
}

fmt.Sprintf("%d records were deleted.", count)
```

### Code Snippet (optional)

```go
// for redis pkg

func (s *Storage) DelWild(key string) (int64, error) {
	if len(key) <= 0 {
		return 0, nil
	}

	res, err := s.db.Eval(ctx, `
		local keysToDelete = redis.call('keys', ARGV[1])
		if #keysToDelete > 0 then
			return redis.call('del', unpack(keysToDelete))
		else
			return 0
		end
	`, []string{key}).Result()

	if err != nil {
		return 0, err
	}

	return res.(int64), nil
}
```

### Checklist:

- [X] I agree to follow Fiber's [Code of Conduct](https://github.com/gofiber/fiber/blob/master/.github/CODE_OF_CONDUCT.md).
- [x] I have checked for existing issues that describe my suggestion prior to opening this one.
- [X] I understand that improperly formatted feature requests may be closed without explanation.

**Comment by gaby** [comment]
@okoseisback You can access the underlaying client by calling `Conn()`.

```go
// Initialize default config
store := redis.New()
client := store.Conn()

// you can Eval() on the client
```

**Comment by gaby** [comment]
@okoseisback Does the above solve your issue?
