### ISSUE TITLE
🤗 [Question]: Release schedule for SQLIte3?

### ISSUE THREAD

**Issue by NicholasGWK** [gofiber/storage#1285]
### Question Description

Hello! I was just wondering if the release process is automated for particular packages, or if there's somewhere I can watch? I noticed SQLite3 hasn't had a release in awhile, and so this commit isn't included: https://github.com/gofiber/storage/commit/3c0019ab86b3e2369da59bcbd4695b71c1e02d80

It fixes a build-time bug I ran into, so I updated to `v2@main`, but just wanted to know how to watch for the official release!

Thanks so much,

NIck

### Code Snippet (optional)

```go
package main

import "github.com/gofiber/storage/%package%"

func main() {
  // Steps to reproduce
}
```

### Checklist:

- [X] I agree to follow Fiber's [Code of Conduct](https://github.com/gofiber/fiber/blob/master/.github/CODE_OF_CONDUCT.md).
- [X] I have checked for existing issues that describe my questions prior to opening this one.
- [X] I understand that improperly formatted questions may be closed without explanation.

**Comment by gaby** [comment]
@NicholasGWK Dependencies updates are automated, the release process is Manual. Usually done by @ReneWerner87 

You can get emails when a new release is done by clicking here and then Custom -> Releases.

![Screenshot_20240317-000957](https://github.com/gofiber/storage/assets/835733/7c09a990-ec7a-40a6-9e05-228e59b0d200)

If your repo is on GitHub you can add a `dependabot.yml` to notify you of new releases:

.github/dependabot.yml
```yaml
version: 2
updates:
    -   package-ecosystem: "gomod"
        directory: "/"
        schedule:
            interval: "daily"
```

@ReneWerner87 Can you trigger a new release of all the storage drivers?

**Comment by NicholasGWK** [comment]
Amazing! Sorry for the delay, I've been traveling. Thanks so much for the detailed explanation + also the subsequent release 🙇 Cheers
