### ISSUE TITLE
[FEATURE] - Add functions: incr, incrBy, incrByFloat

### ISSUE THREAD

**Issue by sujit-baniya** [gofiber/storage#143]
Along with `Set` and `Get` it's better introduce some more functions for data integrity and most of the databases already support above functions.

Some functions:
1) incr
2) incrBy
3) incrByFloat
4) expire

**Comment by efectn** [comment]
@ReneWerner87 @hi019 what do you think about that? I think 1, 2, 3. options would be great.

**Comment by ReneWerner87** [comment]
Well I'm not that excited, for me these are just key value storages and more than fetch or set is not needed from my point of view.

But that's just my opinion and I like to be overvote or convinced

**Comment by YankeeTube** [comment]
Oh, I came because I needed an INCR...
It is shocking to see that the issue was a year and three months ago.

It seems inevitable that I will have to open two REDIS sessions.

**Comment by efectn** [comment]
> Oh, I came because I needed an INCR... It is shocking to see that the issue was a year and three months ago.
> 
> It seems inevitable that I will have to open two REDIS sessions.

You can use https://github.com/gofiber/storage/blob/main/redis/redis.go#L104

**Comment by ReneWerner87** [comment]
access to the db connection is introduced in #451

**Comment by sujit-baniya** [comment]
@ReneWerner87 Yes I think these features: `incr`, `incrBy` and `incrByFloat` will serve high purpose of usability. It's true that for Redis storage we could use `Conn()` function to get client connection to do stuffs. 

But since we have `Storage` interface, most of the developers will use the interface instead of specific driver. That's why I purpose to add these features in interface.

Some of the use cases
1) Manage the metrics by increasing the value on key
2) Managing item counter in queues

**Comment by sujit-baniya** [comment]
For e.g.

I'm building SMS Application and it requires to update SMS counts per user. I plan to use `gofiber/storage`. Since it supports multiple driver, I could easily switch to any drivers I wanted. And if I've mentioned features in `gofiber/storage` interface, I would not need to create connections again per driver (it will create a lot mess then)

**Comment by sujit-baniya** [comment]
@gaby That would help a lot. Thanks :)

**Comment by gaby** [comment]
@sujit-baniya Let me know if this can be closed :-) Thanks!
