### ISSUE TITLE
[Feature request] Let host config allow url string other than IP 

### ISSUE THREAD

**Issue by infinite-sea** [gofiber/storage#362]
Currently when trying to use a cloud based host , such as host=/cloudsql/INSTANCE_CONNECTION_NAME it breaks on line 59 when using url.QueryEscape

**Comment by ReneWerner87** [comment]
Host name is a unix socket path

Example here https://cloud.google.com/sql/docs/postgres/connect-app-engine-standard

Its supported by https://github.com/lib/pq

**Comment by ReneWerner87** [comment]
https://github.com/lib/pq/blob/master/conn.go#L425

Its completely supported, we only have to skip the escaping when the host has a prefix with "/"

https://github.com/gofiber/storage/blob/main/postgres/postgres.go#L59

**Comment by infinite-sea** [comment]
tried creating a PR here https://github.com/gofiber/storage/pull/363
