### ISSUE TITLE
[Feature Request] Support for retrieving database connections from storage structures

### ISSUE THREAD

**Issue by gaby** [gofiber/storage#440]
Provide a way to retrieve the db object from the storage.

Example:
```
store := redis.New()
db := store.DB()
keys := db.keys()
```

Currently theres no way to access the DB from any of the storage drivers, limiting the user options within Fiber.

**Comment by gaby** [comment]
@ReneWerner87 Can this be implemented under v1.x or would it need v2.x since the interface will change?

**Comment by ReneWerner87** [comment]
under v1  because it is no breaking change only a addition

**Comment by gaby** [comment]
@ReneWerner87 I just submitted a PR to fix this issue.
