### ISSUE TITLE
[postgres] Panic after first database ping

### ISSUE THREAD

**Issue by hugmouse** [gofiber/storage#45]
Description: Panic occurs when creating a db for sessions - it occurs when trying to ping the db.

https://github.com/gofiber/storage/blob/2e02bda8a118f2e6d17292bd58a3246f7ba28249/postgres/postgres.go#L72-L75

Error: `panic: pq: database "fiber" does not exist`

## Example 

```go
package main

import (
	"github.com/gofiber/fiber/v2/middleware/session"
	"github.com/gofiber/storage/postgres"
)

var GlobalSessionStore *session.Store

func NewSession() {
	// Initialize default config
	store := postgres.New()
	GlobalSessionStore = session.New(session.Config{Storage: store})
}

func main() {
	NewSession()
}
```

**Comment by hugmouse** [comment]
Oh sorry I'm kinda stupid.

You need to specify database like this: `postgres.New(postgres.Config{Database: "postgres"})`

**Comment by Fenny** [comment]
Yeah, `Database` defaults to `fiber` so unless you have a database named `fiber` you have to provide your own config 👍
