### ISSUE TITLE
[Bug] Database password not URL-encoded

### ISSUE THREAD

**Issue by ph0t0shop** [gofiber/storage#513]
Characters such as `#` and `%` in my password cause issues. `url.QueryEscape`-ing my password solves this issue. I don't find this expected behavior because I am not providing a `ConnectionURI`. When entering a password, I do not expect to be in an environment where I need to manually URL-encode my data.

**Comment by ReneWerner87** [comment]
Which adapter for which storage are we talking about here?

**Comment by ph0t0shop** [comment]
I used `postgres`

**Comment by ReneWerner87** [comment]
but we don´t use the QueryEscape method in the password section
https://github.com/gofiber/storage/blob/d2569fbe93d9723988a073073019a6c325515ede/postgres/postgres.go#L57-L62

can you try it with 
https://github.com/gofiber/storage/blob/main/postgres/postgres.go#L51
ConnectionURI direct and give feedback

**Comment by ReneWerner87** [comment]
@hi019 do you have an idea how this is possible? Can you help here
