### ISSUE TITLE
🐛 memcache utils.Trim undefined latest release

### ISSUE THREAD

**Issue by sixcolors** [gofiber/storage#591]
Using go.mod with:
```
github.com/gofiber/fiber/v2 v2.38.1
github.com/gofiber/storage/memcache v0.0.0-20221005114327-4e6f1c95ff26
```
When trying to run I get
```
# github.com/gofiber/storage/memcache
../go/pkg/mod/github.com/gofiber/storage/memcache@v0.0.0-20221027071415-dca8f183e44b/memcache.go:24:36: undefined: utils.Trim
```

if I change memcache.go line 23 from  `serverList := strings.Split(utils.Trim(cfg.Servers, ' '), ",")` to  `serverList := strings.Split(strings.Trim(cfg.Servers, " "), ",")` it works.

@efectn mentioned utils.Trim was used for performance on older go versions. It seems that this is broken with the latest goofier release when using go 1.19 in my package however.

**Comment by sixcolors** [comment]
utils.Trim is used in memcache.go in one place only `func New(config ...Config) *Storage`

Performance of strings.Trim should not be a concern in this case.

**Comment by ReneWerner87** [comment]
In my experience, it would be better to find out the cause of the problem than to work around it, because other places also use these functions.

Will try it myself tomorrow, but the error looks like it has something to do with the modules and not the function itself.

**Comment by sixcolors** [comment]
> In my experience, it would be better to find out the cause of the problem than to work around it, because other places also use these functions.
> 
> Will try it myself tomorrow, but the error looks like it has something to do with the modules and not the function itself.

It does appear to be an issue with modules. The utils.Trim function has been removed from the current utils package, and it seems that the older version is not working.

go.mod for memcahce package is at go 1.14 while fiber is 1.19

**Comment by ReneWerner87** [comment]
But Version https://github.com/gofiber/storage/blob/main/memcache/go.mod#L7
0.1.2

exists https://github.com/gofiber/utils/releases/tag/v0.1.2

with the Trim function https://github.com/gofiber/utils/blob/v0.1.2/strings.go#L39

**Comment by sixcolors** [comment]
> But Version https://github.com/gofiber/storage/blob/main/memcache/go.mod#L7 0.1.2
> 
> exists https://github.com/gofiber/utils/releases/tag/v0.1.2
> 
> with the Trim function https://github.com/gofiber/utils/blob/v0.1.2/strings.go#L39

I see that; something is deffinatly not working as expected.

**Comment by ReneWerner87** [comment]
> > In my experience, it would be better to find out the cause of the problem than to work around it, because other places also use these functions.
> > 
> > Will try it myself tomorrow, but the error looks like it has something to do with the modules and not the function itself.
> 
> It does appear to be an issue with modules.
> 
> memcache is using `github.com/gofiber/utils` while fiber is using `github.com/gofiber/fiber/v2/utils`
> 
> changing the package to `github.com/gofiber/fiber/v2/utils` also fixes the issue

Okay but why would that be a problem
I know that fiber internally uses the copy of the utils and the external packages use the utils among each other, but why would that be a problem?

**Comment by sixcolors** [comment]
storage package is also using go 1.14 in go.mod and fiber is using go 1.19.... I assume there is either a bug; or maybe I just need to go read the release notes for go to see if there is something that would cause this.

**Comment by ReneWerner87** [comment]
The tests for the memcache storage which use a docker container do not fail either

Can you rule out a local problem? Can only test this with me tomorrow during the day

**Comment by sixcolors** [comment]
I have tested on two systems, but I only get the bug if using in a project with gofiber and storage/memcache individually they both pass.

I will make a sample project with just fiber and memcache to see if there is some other conflict.

**Comment by ReneWerner87** [comment]
Would be really good if we could find out the cause
If the problem is not fixable then gladly with the standard package, but I would find it better to research first to exclude other errors in other packages

**Comment by sixcolors** [comment]
utils.Trim is only used in this one place out of all the storage packages; although all other packages are using github.com/gofiber/utils so I have a good place to test and see if it is somehow using the wrong package with one of the other functions.

**Comment by sixcolors** [comment]
specifying `github.com/gofiber/utils@v0.1.2` makes it work. But running `go get -u .` upgrades "github.com/gofiber/utils" to v1.0.0 and then the package specifid version seems to be ignored.......

**Comment by sixcolors** [comment]
please see demo project https://github.com/sixcolors/gofiber-storage-memcache-modtest

**Comment by sixcolors** [comment]
confirmed the same happens with go version go1.19.2 linux/amd64

**Comment by sixcolors** [comment]
Oh wait!

I see what happened; there are breaking API changes to module github.com/gofiber/utils and it's go mod still has

```
module github.com/gofiber/utils
```

Shouldn't that have been changed to:

```
module github.com/gofiber/utils/v1
```

?

**Comment by ReneWerner87** [comment]
Ok we can change that

**Comment by sixcolors** [comment]
> Ok we can change that

I think you'd have to pull the 1.0.0 release and re-release it with the v1 to stop `go get -u` from upgrading it.

**Comment by efectn** [comment]
> > Ok we can change that
> 
> I think you'd have to pull the 1.0.0 release and re-release it with the v1 to stop `go get -u` from upgrading it.

I think v2 would be better for new changes. And we can release v1.0.1 from old v0.1.2 tag

**Comment by sixcolors** [comment]
> > > Ok we can change that
> > 
> > 
> > I think you'd have to pull the 1.0.0 release and re-release it with the v1 to stop `go get -u` from upgrading it.
> 
> I think v2 would be better for new changes. And we can release v1.0.1 from old v0.1.2 tag

I'm happy, either resolve the issue. ✅

**Comment by ReneWerner87** [comment]
I have created 2 new versions
https://github.com/gofiber/utils/releases/tag/v2.0.0-beta.1
and
https://github.com/gofiber/utils/releases/tag/v1.0.1 with v0.1.2 as source

Can someone check if the new namespace is working https://github.com/gofiber/utils/blob/master/go.mod#L1
```go
module github.com/gofiber/utils/v2
```

and the errors for the old version are fixed ?

**Comment by sixcolors** [comment]
> I have created 2 new versions https://github.com/gofiber/utils/releases/tag/v2.0.0-beta.1 and https://github.com/gofiber/utils/releases/tag/v1.0.1 with v0.1.2 as source
> 
> Can someone check if the new namespace is working https://github.com/gofiber/utils/blob/master/go.mod#L1
> 
> ```go
> module github.com/gofiber/utils/v2
> ```
> 
> and the errors for the old version are fixed ?

confirmed working using test project https://github.com/sixcolors/gofiber-storage-memcache-modtest
