### ISSUE TITLE
Consider tagging submodule?

### ISSUE THREAD

**Issue by Rick-xuy** [gofiber/storage#711]
I found that package `github.com/gofiber/storage/redis` is placed in submodule `github.com/gofiber/storage/redis` instead of root module. <br>
However, it seems that submodule `github.com/gofiber/storage/redis` is not tagged. According to [Go Modules wiki](https://github.com/golang/go/wiki/Modules#is-it-possible-to-add-a-module-to-a-multi-module-repository), submodule should be tagged like `relative-path-to-root/vX.X.X`.
At now, when trying to import package `github.com/gofiber/storage/redis`, downstream would depends on **pseudo-version** of module `github.com/gofiber/storage/redis`.
```
github.com/gofiber/storage/redis v0.0.0-20220523092334-6d96fb56afb5
```
I think it is not very readable and difficult to upgrade. This is not conductive to version control either.
So, I propose whether it is possible to tag submodule properly. For example, `redis/v0.0.1`, `redis/v1.3.3`etc, so that other project can use tag to import this module in go.mod.

**Comment by gaby** [comment]
Relate: https://github.com/gofiber/contrib/issues/470
