### ISSUE TITLE
🤗 [Question]: panic EOF

### ISSUE THREAD

**Issue by louisunlimited** [gofiber/storage#854]
### Question Description

I have an existing remote redis connection on a upstash account, but when I tried to create a new redis connection with the same connection string I get 
```bash
panic: EOF
```

My code looks like this:
```go
	storage := redis.New(redis.Config{
		URL:     "redis://xxx:xxxxxxxx@exciting-grouse-30789.upstash.io:12345",
		Reset:    false,
	})
```
when I switch to using only `redis.New()` on localhost it seems to work properly. Does this package only run on localhost?

(I also tried to comment out my other redis connection but the above error still exits.)

Thanks a lot!

### Checklist:

- [X] I agree to follow Fiber's [Code of Conduct](https://github.com/gofiber/fiber/blob/master/.github/CODE_OF_CONDUCT.md).
- [X] I have checked for existing issues that describe my questions prior to opening this one.
- [X] I understand that improperly formatted questions may be closed without explanation.

**Comment by gaby** [comment]
@louisunlimited You are missing the DB identifier:

```go
store = redis.New(redis.Config{
    URL:     "redis://<user>:<pass>@127.0.0.1:6379/<db>",
    Reset:    false,
})
```

**Comment by louisunlimited** [comment]
> @louisunlimited You are missing the DB identifier:
> 
> ```go
> store = redis.New(redis.Config{
>     URL:     "redis://<user>:<pass>@127.0.0.1:6379/<db>",
>     Reset:    false,
> })
> ```
> 
> Which could be triggering this part of the config.go
> 
> ```go
> if cfg.URL != "" {
> 		options, err := redis.ParseURL(cfg.URL)
> 		if err != nil {
> 			panic(err)
> 		}
> ```

Yes I saw this in the docs but the connection string upstash provided me does not have this db name included 🤔 and my other redis connected just fine without so I'm confused

**Comment by gaby** [comment]
> > @louisunlimited You are missing the DB identifier:
> > ```go
> > store = redis.New(redis.Config{
> >     URL:     "redis://<user>:<pass>@127.0.0.1:6379/<db>",
> >     Reset:    false,
> > })
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Which could be triggering this part of the config.go
> > ```go
> > if cfg.URL != "" {
> > 		options, err := redis.ParseURL(cfg.URL)
> > 		if err != nil {
> > 			panic(err)
> > 		}
> > ```
> 
> Yes I saw this in the docs but the connection string upstash provided me does not have this db name included 🤔 and my other redis connected just fine without so I'm confused

The docs state it's required for ParseURL: https://pkg.go.dev/github.com/redis/go-redis/v9#ParseURL

Try this:

```
	storage := redis.New(redis.Config{
		URL:     "redis://xxx:xxxxxxxx@exciting-grouse-30789.upstash.io:12345/0",
		Reset:    false,
	})
```

Usually the default DB in Redis is `0`

**Comment by louisunlimited** [comment]
> > > @louisunlimited You are missing the DB identifier:
> > > ```go
> > > store = redis.New(redis.Config{
> > >     URL:     "redis://<user>:<pass>@127.0.0.1:6379/<db>",
> > >     Reset:    false,
> > > })
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > Which could be triggering this part of the config.go
> > > ```go
> > > if cfg.URL != "" {
> > > 		options, err := redis.ParseURL(cfg.URL)
> > > 		if err != nil {
> > > 			panic(err)
> > > 		}
> > > ```
> > 
> > 
> > Yes I saw this in the docs but the connection string upstash provided me does not have this db name included 🤔 and my other redis connected just fine without so I'm confused
> 
> The docs state it's required for ParseURL: https://pkg.go.dev/github.com/redis/go-redis/v9#ParseURL
> 
> Try this:
> 
> ```
> 	storage := redis.New(redis.Config{
> 		URL:     "redis://xxx:xxxxxxxx@exciting-grouse-30789.upstash.io:12345/0",
> 		Reset:    false,
> 	})
> ```
> 
> Usually the default DB in Redis is `0`

I've tried this approach already and it didn't work 😭

```go
store := redis.New(redis.Config{
	Host:      "exciting-grouse-30789.upstash.io",
	Port:      12345,
	Username:  "xxx",
	Password:  "xxxx",
	Database:  0,
	Reset:     false,
	TLSConfig: nil,
	PoolSize:  10 * runtime.GOMAXPROCS(0),
})
```

**Comment by gaby** [comment]
What is the error saying?

**Comment by louisunlimited** [comment]
```
panic: EOF

goroutine 1 [running]:
github.com/gofiber/storage/redis/v2.New({0x1400050fde8?, 0x1050b08ec?, 0x1054163a0?})
        /Users/louissssss/go/pkg/mod/github.com/gofiber/storage/redis/v2@v2.0.2/redis.go:56 +0x3e0
github.com/my_proj_name/middlewares.setUpSessionAuth(0x1400031fed8?)
        /Users/louissssss/Desktop/my_proj_name/middlewares/session.go:21 +0x60
github.com/....
```

**Comment by gaby** [comment]
> > > > @louisunlimited You are missing the DB identifier:
> > > > ```go
> > > > store = redis.New(redis.Config{
> > > >     URL:     "redis://<user>:<pass>@127.0.0.1:6379/<db>",
> > > >     Reset:    false,
> > > > })
> > > > ```
> > > > 
> > > > 
> > > >     
> > > >       
> > > >     
> > > > 
> > > >       
> > > >     
> > > > 
> > > >     
> > > >   
> > > > Which could be triggering this part of the config.go
> > > > ```go
> > > > if cfg.URL != "" {
> > > > 		options, err := redis.ParseURL(cfg.URL)
> > > > 		if err != nil {
> > > > 			panic(err)
> > > > 		}
> > > > ```
> > > 
> > > 
> > > Yes I saw this in the docs but the connection string upstash provided me does not have this db name included 🤔 and my other redis connected just fine without so I'm confused
> > 
> > 
> > The docs state it's required for ParseURL: [pkg.go.dev/github.com/redis/go-redis/v9#ParseURL](https://pkg.go.dev/github.com/redis/go-redis/v9#ParseURL)
> > Try this:
> > ```
> > 	storage := redis.New(redis.Config{
> > 		URL:     "redis://xxx:xxxxxxxx@exciting-grouse-30789.upstash.io:12345/0",
> > 		Reset:    false,
> > 	})
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Usually the default DB in Redis is `0`
> 
> I've tried this approach already and it didn't work 😭
> 
> ```go
> store := redis.New(redis.Config{
> 	Host:      "exciting-grouse-30789.upstash.io",
> 	Port:      12345,
> 	Username:  "xxx",
> 	Password:  "xxxx",
> 	Database:  0,
> 	Reset:     false,
> 	TLSConfig: nil,
> 	PoolSize:  10 * runtime.GOMAXPROCS(0),
> })
> ```

Is that a typo, the port 12345, instead of 6379?

**Comment by louisunlimited** [comment]
No it's a assigned port by upstash, I changed it to 12345 here for simplicity sake)

**Comment by gaby** [comment]
@louisunlimited Actually looking at your stacktrace, it's failing here:

```go
if err := db.Ping(context.Background()).Err(); err != nil {
		panic(err)
	}
```

So it's parsing correctly, but it can't reach the DB. Is this instance using TLS? Else the password is going plaintext

**Comment by louisunlimited** [comment]
> @louisunlimited Actually looking at your stacktrace, it's failing here:
> 
> ```go
> if err := db.Ping(context.Background()).Err(); err != nil {
> 		panic(err)
> 	}
> ```
> 
> So it's parsing correctly, but it can't reach the DB. Is this instance using TLS? Else the password is going plaintext

Yes, the instance is using TLS

**Comment by gaby** [comment]
> > @louisunlimited Actually looking at your stacktrace, it's failing here:
> > ```go
> > if err := db.Ping(context.Background()).Err(); err != nil {
> > 		panic(err)
> > 	}
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > So it's parsing correctly, but it can't reach the DB. Is this instance using TLS? Else the password is going plaintext
> 
> Yes, the instance is using TLS

Then you need to create a `tls.Config` object and pass it to `redis.Config()`. There's an example in the unit-tests here: https://github.com/gofiber/storage/blob/main/redis/redis_test.go#L152

**Comment by louisunlimited** [comment]
> > > @louisunlimited Actually looking at your stacktrace, it's failing here:
> > > ```go
> > > if err := db.Ping(context.Background()).Err(); err != nil {
> > > 		panic(err)
> > > 	}
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > So it's parsing correctly, but it can't reach the DB. Is this instance using TLS? Else the password is going plaintext
> > 
> > 
> > Yes, the instance is using TLS
> 
> Then you need to create a `tls.Config` object and pass it to `redis.Config()`. There's an example in the unit-tests here: https://github.com/gofiber/storage/blob/main/redis/redis_test.go#L152

Thanks! Do you mind if I ask how can I get `client.crt` and `client.key`?

**Comment by gaby** [comment]
> 

I think you can create one without x509 pair:

```go
tlsCfg := &tls.Config{
		MinVersion:               tls.VersionTLS12,
		CurvePreferences:         []tls.CurveID{tls.CurveP521, tls.CurveP384, tls.CurveP256},
		PreferServerCipherSuites: true,
		CipherSuites: []uint16{
			tls.TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384,
			tls.TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA,
			tls.TLS_RSA_WITH_AES_256_GCM_SHA384,
			tls.TLS_RSA_WITH_AES_256_CBC_SHA,
		},
	}
```

**Comment by louisunlimited** [comment]
> > 
> 
> I think you can create one without x509 pair:
> 
> ```go
> tlsCfg := &tls.Config{
> 		MinVersion:               tls.VersionTLS12,
> 		CurvePreferences:         []tls.CurveID{tls.CurveP521, tls.CurveP384, tls.CurveP256},
> 		PreferServerCipherSuites: true,
> 		CipherSuites: []uint16{
> 			tls.TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384,
> 			tls.TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA,
> 			tls.TLS_RSA_WITH_AES_256_GCM_SHA384,
> 			tls.TLS_RSA_WITH_AES_256_CBC_SHA,
> 		},
> 	}
> ```

This worked perfectly, thank you so much!

**Comment by gaby** [comment]
@louisunlimited Awesome to hear. I will add a TLS example and new test case today. To cover this case without x509 pair
