### ISSUE TITLE
cannot import memory v2 package

### ISSUE THREAD

**Issue by RHIE-coder** [gofiber/storage#966]
I've tried importing the `github.com/gofiber/storage/memory/v2`, but I'm encountering an error the message below.

```sh
$ go get github.com/gofiber/storage/memory/v2
   [STDOUT]
    go: module github.com/gofiber/storage/memory@upgrade found (v1.3.4), but does not contain package github.com/gofiber/storage/memory/v2
```
My Golang version is `go version go1.20.2`

Am I doing something wrong?

https://github.com/gofiber/storage/blob/a1405af086c90e4f820bae167de69765385a7361/memory/README.md?plain=1#L43

**Comment by ReneWerner87** [comment]
hmm but v2 memory is not release right now (just in the master)
and v1.3.4 is without "/v2" suffix

https://github.com/gofiber/storage/blob/memory/v1.3.4/memory/go.mod#L1C41-L1C41

@gaby @efectn do you have an idea?

**Comment by efectn** [comment]
It looks like we forgot adding tag for memory v2

**Comment by RHIE-coder** [comment]
@efectn `go get github.com/gofiber/storage/memory/v2@main` works well.

### - go get

```sh
$ go get github.com/gofiber/storage/memory/v2@main
  [STDOUT]
    go: added github.com/gofiber/storage/memory/v2 v2.0.0-20230828073434-a1405af086c9
```

### - `go.mod`

```
go 1.20

require github.com/gofiber/storage/memory/v2 v2.0.0-20230828073434-a1405af086c9 // indirect
```

### - `main.go`

```go
package main

import (
	"fmt"

	memory "github.com/gofiber/storage/memory/v2"
)

func main() {

	store := memory.New()

	err := store.Set("key1", []byte("test"), 100000000000)

	if err != nil {
		panic(err)
	}

	result, err := store.Get("key1")

	if err != nil {
		panic(err)
	}

	fmt.Println(string(result)) //test
}
```

**Comment by ReneWerner87** [comment]
@RHIE-coder can you share your original go mod and the import places for the package? did you try to use multiple packages in the same project ?

> It looks like we forgot adding tag for memory v2

not really, that was intentional from me
since in version 2 currently only the not support go versions before 1.19 were and no other features, I have this release first not yet made that other features with possible other breaking changes with version 2 can come and we do not have to 2 times the version raise

this case is also valid that we wait with the releases until they have reached a state and then release only

the question is, what was it with the go module dependencies manager that made them try to pull version 2 even though it wasn't released yet?

**Comment by RHIE-coder** [comment]
@ReneWerner87 I truly don't understand why, but I tried again in a new device environment to inform you about my situation and problems. Suddenly, it works. So, I went back to the device where the issue occurred and tried again, and it works there too. It's really confusing. I'm not sure what the problem was or why I can suddenly import the module, but somehow it seems to have been resolved.

Thank you all for providing immediate feedback. @efectn @ReneWerner87

### when the issue occured
![image](https://github.com/gofiber/storage/assets/47167847/707ba88e-14e1-4323-b766-34a800e477df)

### other device
![image](https://github.com/gofiber/storage/assets/47167847/5526ff02-52d1-4d52-b812-3898f1fb92b3)

### return to the device where the issue occurred and trying again
![image](https://github.com/gofiber/storage/assets/47167847/a9666032-daae-4427-b7cf-e44f38210973)

**Comment by ReneWerner87** [comment]
but why do you download memory/v2 , as already mentioned it is not yet ready and not yet tagged

where in the code is this needed?

**Comment by RHIE-coder** [comment]
https://docs.gofiber.io/storage/memory/

Because I was instructed to download memory/v2 from the official Go Fiber website.

**Comment by ReneWerner87** [comment]
ok thx for the hint
i improved the documentation 
https://github.com/gofiber/docs/commit/f383636175aceb20d1cf4b5b9b6413d84e091ab3

now there is a banner which says that this is not yet live
