### ISSUE TITLE
🚀 [Feature]: s3: support setting with checksum

### ISSUE THREAD

**Issue by iredmail** [gofiber/storage#970]
### Feature Description

I understand current s3 implementation is designed for gofiber Storage interface, but it could be used as a s3 library too.

My question is, do you accept PR to add a new function alternative to `Set()` to accept checksum (e.g. sha256)? so that S3 server will verify the data integrity on server side.

Current `Set()` doesn't accept any checksum:

https://github.com/gofiber/storage/blob/main/s3/s3.go#L95C39-L99

The plan is adding new functions to accept checksum like below (since theses functions are not designed for Storage interface, i removed `exp time.Duration`):
```
SetWithChecksumCRC32(key string, val []byte, checksum string)
SetWithChecksumCRC32C(key string, val []byte, checksum string)
SetWithChecksumSHA1(key string, val []byte, checksum string)
SetWithChecksumSHA256(key string, val []byte, checksum string)
```

Or, one function to support all (`checksum map[string]string`, key is checksum algorithm like `CRC32`, `SHA256`, value is the checksum):
```
SetWithChecksum(key string, val []byte, checksum map[string]string)
```

Your opinion?

### Checklist:

- [X] I agree to follow Fiber's [Code of Conduct](https://github.com/gofiber/fiber/blob/master/.github/CODE_OF_CONDUCT.md).
- [X] I have checked for existing issues that describe my suggestion prior to opening this one.
- [X] I understand that improperly formatted feature requests may be closed without explanation.

**Comment by gaby** [comment]
@ReneWerner87 How do we handle adding functions outside the `Storage.go` interface?

Can they be allowed as long as the main functions are implemented as expected?

**Comment by gaby** [comment]
The PR for minio is already adding a func to the interface `CheckBucket()`. https://github.com/gofiber/storage/pull/962

@iredmail To me it makes more sense to add: `SetWithChecksum()`

**Comment by ReneWerner87** [comment]
> @ReneWerner87 How do we handle adding functions outside the `Storage.go` interface?
> 
> Can they be allowed as long as the main functions are implemented as expected?

yes, as with the templates it is only important that the core is the same, the rest can vary
