### ISSUE TITLE
🐛 [Bug]: redis: client is closed error

### ISSUE THREAD

**Issue by alparslanahmed** [gofiber/storage#990]
### Bug Description

I am using RedisStore in my application and this error comes from nowhere. On my pc when i try to get some key from Redis "redis: client is closed" comes sometimes. But on the server its always disconnected.

```go
// Redis Client
var RedisStore = redis.New()

// When accessing redis
var redis = database.RedisStore.Conn()
var state = redis.Get(ctx, fmt.Sprintf("state.user.%d", user.ID))
if state.Err() != nil {}
```

### How to Reproduce

1. Create new RedisStore
2. Try to access some key from store

### Expected Behavior

It gives the value from store without error

### Storage package Version

v1.3.4

### Code Snippet (optional)

```go
package database

import "github.com/gofiber/storage/redis"

var RedisStore = redis.New()
```

### Checklist:

- [X] I agree to follow Fiber's [Code of Conduct](https://github.com/gofiber/fiber/blob/master/.github/CODE_OF_CONDUCT.md).
- [X] I have checked for existing issues that describe my problem prior to opening this one.
- [X] I understand that improperly formatted bug reports may be closed without explanation.

**Comment by gaby** [comment]
@alparslanahmed You are using the default store:

```go
var RedisStore = redis.New()
```

Is your redis instance at `localhost:6379` and doesnt use username, password, and default DB?

**Comment by gaby** [comment]
Also update your import, you are 2 major versions behind. The current module is here `go get github.com/gofiber/storage/redis/v3`

**Comment by alparslanahmed** [comment]
> @alparslanahmed You are using the default store:
> 
> ```go
> var RedisStore = redis.New()
> ```
> 
> Is your redis instance at `localhost:6379` and doesnt use username, password, and default DB?

Yes it is

**Comment by gaby** [comment]
> > @alparslanahmed You are using the default store:
> > ```go
> > var RedisStore = redis.New()
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Is your redis instance at `localhost:6379` and doesnt use username, password, and default DB?
> 
> Yes it is

Can you upgrade to `V3` and try again?

**Comment by gaby** [comment]
@alparslanahmed Were you able to figured out your issue?

**Comment by alparslanahmed** [comment]
I upgraded to v3 but issue persist :(

```go
package database

import "github.com/gofiber/storage/redis/v3"

var RedisStore = redis.New()
```

**Comment by gaby** [comment]
@alparslanahmed Can you share your logs?

**Comment by alparslanahmed** [comment]
This is the error, which logs you need?

```
redis: client is closed
```

**Comment by gaby** [comment]
@alparslanahmed How are you running Redis?

**Comment by alparslanahmed** [comment]
I run redis on Ubuntu, same server with the application.

**Comment by alparslanahmed** [comment]
Redis running as systemd service

![image](https://github.com/gofiber/storage/assets/5161926/c7b72bf6-aaa3-4fc9-a01e-bade9e7525a4)

**Comment by ReneWerner87** [comment]
```go
package main

import (
	"github.com/gofiber/fiber/v2"
	"github.com/gofiber/storage/redis/v3"
	"log"
)

func main() {
	store := redis.New()

	app := fiber.New()
	app.Get("/hello", func(c *fiber.Ctx) error {
		err := store.Set("hello", []byte("world"), 0)
		if err != nil {
			log.Fatalln(err)
		}

		sendText, err := store.Get("hello")
		if err != nil {
			log.Fatalln(err)
		}
        
		return c.Send(sendText)
	})
	log.Fatalln(app.Listen(":3000"))
}

```
![image](https://github.com/gofiber/storage/assets/7063188/64186e44-35c2-4c5f-9759-9ee1a4200242)


We need a reproducible example, without it we cannot make or help a fix

please try to create a small example where the error is reproducible

**Comment by gaby** [comment]
@alparslanahmed Did you figured out your issue?

**Comment by gaby** [comment]
@ReneWerner87 this can be closed
