### ISSUE TITLE
🤗 [feature]: Add support for Keys() to Redis and Memory drivers

### ISSUE THREAD

**Issue by glimchb** [gofiber/storage#995]
### Question Description

Is there a plan to extend this interface to support fetching all keys? 

### Code Snippet (optional)

```go
package main

import "github.com/gofiber/storage/%package%"

func main() {
  // Steps to reproduce
}
```

### Checklist:

- [X] I agree to follow Fiber's [Code of Conduct](https://github.com/gofiber/fiber/blob/master/.github/CODE_OF_CONDUCT.md).
- [X] I have checked for existing issues that describe my questions prior to opening this one.
- [X] I understand that improperly formatted questions may be closed without explanation.

**Comment by gaby** [comment]
@glimchb This would normally be easy, but each DB has their own way, some don't even support this. For example with redis you can do this

```go
store := redis.New()
keys := store.Conn().Keys()
```

**Comment by glimchb** [comment]
understood @gaby 

so no plans to add this new function to the interface [itself](https://github.com/gofiber/storage/blob/main/storage.go) or it is under consideration ?

**Comment by gaby** [comment]
@glimchb We can easily add it to Redis and Rueidis. Do you have any specific driver in mind that you need?

**Comment by glimchb** [comment]
Thank you @gaby

yes, Redis for production and memory for mocking

**Comment by gaby** [comment]
@glimchb I will work on adding that to redis and rueidis this week

**Comment by glimchb** [comment]
@gaby appreciate this!

**Comment by gaby** [comment]
@glimchb ListAll, GetAll, Keys are all pretty much the same right?

I'm going with `Keys()`, which is the same name that Redis uses.

**Comment by gaby** [comment]
@glimchb PR's have been submitted for both `Redis` and `Memory`

**Comment by glimchb** [comment]
> I'm going with `Keys()`, which is the same name that Redis uses.
excellent!

**Comment by glimchb** [comment]
> @glimchb PR's have been submitted for both `Redis` and `Memory`

one small comment on reds PR #1052

**Comment by gaby** [comment]
Fixed via #1052 #1053 pending Release of new Redis/Memory drivers

**Comment by gaby** [comment]
@glimchb New releases are out, for memory the major version changed to v2.0.0, for Redis it's under v3.1.0

**Comment by glimchb** [comment]
> @glimchb New releases are out, for memory the major version changed to v2.0.0, for Redis it's under v3.1.0

amazing!

**Comment by glimchb** [comment]
@gaby at some point, once added to ALL implementations, there will be `Keys()` in the interface as well, right ?
https://github.com/gofiber/storage/blob/main/storage.go

**Comment by gaby** [comment]
@glimchb I'm not sure how easy its going to be to add this to all drivers. Some of them require slow performing queries to even get all the keys. At least with memory/redis/rueidis it is easy.
